
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BatchNumberMaster
{

    public int ID { get; set; }

    public Nullable<int> ProductionIndentId { get; set; }

    public string BatchNumber { get; set; }

    public string WorkOrderNumber { get; set; }

    public Nullable<int> SO_Id { get; set; }

    public Nullable<bool> flagForIndent { get; set; }

    public Nullable<int> ProductID { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual ProductionIndent ProductionIndent { get; set; }

    public virtual SalesOrder SalesOrder { get; set; }

}

}
