//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchPlanning_Details
    {
        public int ID { get; set; }
        public Nullable<int> BatchPlanningId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<decimal> QuantityPercentage { get; set; }
        public Nullable<decimal> BatchSize { get; set; }
        public Nullable<decimal> TotalQuantityInBatch { get; set; }
        public Nullable<decimal> YieldPercentage { get; set; }
        public Nullable<decimal> ActualRequirement { get; set; }
        public Nullable<decimal> StockInHand { get; set; }
        public Nullable<decimal> ToBeProcured { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual BatchPlanningMaster BatchPlanningMaster { get; set; }
        public virtual Item Item { get; set; }
    }
}
