
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class CertificateAnalysi
{

    public int Id { get; set; }

    public string Source { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string WOPO { get; set; }

    public string ProductName { get; set; }

    public string BatchNo { get; set; }

    public string PackingSize { get; set; }

    public Nullable<System.DateTime> BestBeforeDate { get; set; }

    public string ClostridiumPerfringens { get; set; }

    public string Salmonella { get; set; }

    public string EscherichiaColi { get; set; }

    public string TotalPlateCountNumber { get; set; }

    public string YeastMould { get; set; }

    public string Coliform { get; set; }

    public string Acidity { get; set; }

    public string PH { get; set; }

    public string TotalSolubleSolids { get; set; }

    public string PeroxideValue { get; set; }

    public string SaltContent { get; set; }

    public string LabAnalysisReportNo { get; set; }

    public string LabAnalysisReport { get; set; }

    public string Verifiedby { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

}

}
