//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientEmailId { get; set; }
        public string ContactPersonName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string ContactNo { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string GSTINNo { get; set; }
        public Nullable<int> BlackList { get; set; }
        public string ShipToAddress { get; set; }
        public Nullable<int> ShipToCountry { get; set; }
        public Nullable<int> ShipToState { get; set; }
        public Nullable<int> ShipToCity { get; set; }
        public string ShipPinCode { get; set; }
        public string ShipStateCode { get; set; }
        public string BillToAddress { get; set; }
        public Nullable<int> BillToCountry { get; set; }
        public Nullable<int> BillToState { get; set; }
        public Nullable<int> BillToCity { get; set; }
        public string BillPinCode { get; set; }
        public string BillStateCode { get; set; }
        public string PanNo { get; set; }
        public string FSSAI { get; set; }
        public string CountryCode { get; set; }
        public string TypeOfCompany { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
