//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COAMaster
    {
        public int COAID { get; set; }
        public string COANo { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<int> LabID { get; set; }
        public Nullable<System.DateTime> COADate { get; set; }
        public Nullable<int> ItemCategoryID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemCode { get; set; }
        public string BatchNo { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> ManufecturingDate { get; set; }
        public Nullable<System.DateTime> BestBefore { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> PackingSize { get; set; }
        public Nullable<double> Acidity { get; set; }
        public Nullable<double> Salt { get; set; }
        public Nullable<double> PH { get; set; }
        public string BRIX { get; set; }
        public Nullable<bool> Consistency { get; set; }
        public Nullable<bool> Ecoli { get; set; }
        public Nullable<bool> YestAndMold { get; set; }
        public Nullable<double> ArobicCount { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
