//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitNote
    {
        public int DebitNoteId { get; set; }
        public Nullable<int> RejectionNoteId { get; set; }
        public Nullable<int> GRNId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string DebitNoteNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Grandtotal { get; set; }
        public string GeneralRemarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedby { get; set; }
    }
}
