
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DebitNoteDetail
{

    public int ID { get; set; }

    public Nullable<int> DebitNoteId { get; set; }

    public Nullable<int> ItemId { get; set; }

    public string Item_Name { get; set; }

    public string Item_Code { get; set; }

    public string ItemTaxValue { get; set; }

    public string ItemUnit { get; set; }

    public Nullable<decimal> ItemUnitPrice { get; set; }

    public Nullable<double> POQuantity { get; set; }

    public Nullable<double> DebitedQuantity { get; set; }

    public Nullable<double> ItemTotalAmount { get; set; }

    public Nullable<int> CurrencyID { get; set; }

    public string CurrencyName { get; set; }

    public Nullable<double> CurrencyPrice { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedby { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual CurrencyMaster CurrencyMaster { get; set; }

    public virtual DebitNote DebitNote { get; set; }

    public virtual Item Item { get; set; }

}

}
