//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryChallanItemDetail
    {
        public int ID { get; set; }
        public Nullable<int> DeliveryChallanID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public string ItemName { get; set; }
        public string Item_Code { get; set; }
        public Nullable<decimal> ItemUnitPrice { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<decimal> OutwardQuantity { get; set; }
        public Nullable<decimal> OrderedQuantity { get; set; }
        public Nullable<double> BalanceQuantity { get; set; }
        public string ItemTaxValue { get; set; }
        public Nullable<double> TotalItemCost { get; set; }
        public string HSN_Code { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> CurrencyPrice { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual DeliveryChallan DeliveryChallan { get; set; }
        public virtual Item Item { get; set; }
    }
}
