//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryChallan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryChallan()
        {
            this.DeliveryChallanItemDetails = new HashSet<DeliveryChallanItemDetail>();
        }
    
        public int ID { get; set; }
        public string DeliveryChallanNumber { get; set; }
        public Nullable<System.DateTime> DeliveryChallanDate { get; set; }
        public Nullable<int> SO_Id { get; set; }
        public string SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public Nullable<int> IndentID { get; set; }
        public string IndentNo { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public string SupplierAddress { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string CompanyName { get; set; }
        public string ShippingAddress { get; set; }
        public string Signature { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> CurrencyPrice { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> TotalAfterTax { get; set; }
        public Nullable<double> OtherTax { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<int> TermsAndCondition_ID { get; set; }
        public string Terms { get; set; }
        public Nullable<bool> IsReturnable { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual Indent Indent { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual TermsAndConditionMaster TermsAndConditionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryChallanItemDetail> DeliveryChallanItemDetails { get; set; }
    }
}
