
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Department
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {

        this.UserDetails = new HashSet<UserDetail>();

    }


    public int DepartmentID { get; set; }

    public string DepartmentName { get; set; }

    public Nullable<int> BranchId { get; set; }

    public string ContactNo { get; set; }

    public string ContactPerson { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> LastModifiedby { get; set; }



    public virtual Branch Branch { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDetail> UserDetails { get; set; }

}

}
