
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class HotFillingPackingLineLogSheetCCP
{

    public int ID { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string ItemName { get; set; }

    public Nullable<System.TimeSpan> ReleaseTime { get; set; }

    public string HotLineTemp { get; set; }

    public string ProductTemp { get; set; }

    public string CleaningHygine { get; set; }

    public Nullable<decimal> RandomWeight { get; set; }

    public string MonitoringParameters { get; set; }

    public string MonitoringFilling { get; set; }

    public string NoOfPouches { get; set; }

    public string Remarks { get; set; }

    public string CorrectiveActions { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

}

}
