
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Indent
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Indent()
    {

        this.DeliveryChallans = new HashSet<DeliveryChallan>();

        this.Indent_Details = new HashSet<Indent_Details>();

        this.PurchaseOrders = new HashSet<PurchaseOrder>();

        this.RequestForQuotations = new HashSet<RequestForQuotation>();

    }


    public int ID { get; set; }

    public string IndentNo { get; set; }

    public Nullable<System.DateTime> IndentDate { get; set; }

    public Nullable<System.DateTime> IndentDueDate { get; set; }

    public Nullable<int> RaisedBy { get; set; }

    public string Description { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> LocationId { get; set; }

    public string LocationName { get; set; }

    public Nullable<int> DesignationId { get; set; }

    public string DesignationName { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string UserName { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeliveryChallan> DeliveryChallans { get; set; }

    public virtual DesignationMaster DesignationMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Indent_Details> Indent_Details { get; set; }

    public virtual LocationMaster LocationMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequestForQuotation> RequestForQuotations { get; set; }

}

}
