
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class InvoiceMaster
{

    public int InvoiceId { get; set; }

    public string DANo { get; set; }

    public Nullable<System.DateTime> DADate { get; set; }

    public string InvoiceNo { get; set; }

    public Nullable<System.DateTime> InvoiceDate { get; set; }

    public string InvoiceType { get; set; }

    public string DateOfIssue { get; set; }

    public string DateOfRemoval { get; set; }

    public string TimeOfIssue { get; set; }

    public string TimeOfRemoval { get; set; }

    public string NotificationNo { get; set; }

    public Nullable<int> CheckedById { get; set; }

    public Nullable<int> ApprovedById { get; set; }

    public Nullable<int> ApprovalStatus { get; set; }

    public string ApprovalRemarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedById { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedById { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

}

}
