
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class InwardQC
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InwardQC()
    {

        this.GRN_Master = new HashSet<GRN_Master>();

        this.InwardQCDetails = new HashSet<InwardQCDetail>();

        this.RejectionNotes = new HashSet<RejectionNote>();

    }


    public int ID { get; set; }

    public Nullable<int> InwardNote_Id { get; set; }

    public string InwardNumber { get; set; }

    public string InwardQCNo { get; set; }

    public Nullable<System.DateTime> InwardQCDate { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GRN_Master> GRN_Master { get; set; }

    public virtual InwardNote InwardNote { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InwardQCDetail> InwardQCDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RejectionNote> RejectionNotes { get; set; }

}

}
