//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueNote
    {
        public int IssueNoteId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string IssueNoteNo { get; set; }
        public Nullable<int> IsAgainstBOM { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<System.DateTime> IssueNoteDate { get; set; }
        public string PONumber { get; set; }
        public string WorkOrderNumber { get; set; }
        public string BatchNo { get; set; }
        public string VendorName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedby { get; set; }
    }
}
