
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class LabMaster
{

    public int LabID { get; set; }

    public Nullable<int> LocationID { get; set; }

    public Nullable<int> FGSID { get; set; }

    public string LabName { get; set; }

    public string LabReport { get; set; }

    public Nullable<int> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual FinishGoodSery FinishGoodSery { get; set; }

    public virtual LocationMaster LocationMaster { get; set; }

}

}
