
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class OilAnalysi
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string time { get; set; }

    public string LotNo { get; set; }

    public string SampleName { get; set; }

    public Nullable<decimal> ACIDValue { get; set; }

    public string PeroxideValue { get; set; }

    public string Color { get; set; }

    public string Flavour { get; set; }

    public string Odour { get; set; }

    public string VerifyByName { get; set; }

    public string Remark { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

}

}
