
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class OutwardNote
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OutwardNote()
    {

        this.OutwardNoteDetails = new HashSet<OutwardNoteDetail>();

    }


    public int ID { get; set; }

    public string OutwardNumber { get; set; }

    public Nullable<System.DateTime> OutwardDate { get; set; }

    public Nullable<int> LocationID { get; set; }

    public string LocationName { get; set; }

    public string LocationAddress { get; set; }

    public string DeliveryAddress { get; set; }

    public string DispatchThrough { get; set; }

    public string DocketNumber { get; set; }

    public string ContactPerson { get; set; }

    public string ContactInformation { get; set; }

    public Nullable<bool> IsReturnable { get; set; }

    public string Remarks { get; set; }

    public string Signature { get; set; }

    public Nullable<int> VerifiedBy { get; set; }

    public string VerifiedByName { get; set; }

    public string VehicleNo { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual LocationMaster LocationMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OutwardNoteDetail> OutwardNoteDetails { get; set; }

}

}
