
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PostProductionRejectionNote_Details
{

    public int ID { get; set; }

    public Nullable<int> PostProdRejectionID { get; set; }

    public Nullable<int> ItemId { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public Nullable<double> ItemUnitPrice { get; set; }

    public string ItemUnit { get; set; }

    public string ItemTaxValue { get; set; }

    public Nullable<int> CurrencyID { get; set; }

    public string CurrencyName { get; set; }

    public Nullable<double> CurrencyPrice { get; set; }

    public Nullable<double> TotalQuantity { get; set; }

    public Nullable<double> RejectedQuantity { get; set; }

    public Nullable<double> OrderedQuantity { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual PostProductionRejectionNote PostProductionRejectionNote { get; set; }

}

}
