
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PostProductionRejectionNote
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PostProductionRejectionNote()
    {

        this.PostProductionRejectionNote_Details = new HashSet<PostProductionRejectionNote_Details>();

    }


    public int ID { get; set; }

    public string PostProdRejectionNoteNo { get; set; }

    public Nullable<System.DateTime> PostProdRejectionNoteDate { get; set; }

    public string PostProdRejectionType { get; set; }

    public Nullable<bool> DraftFlag { get; set; }

    public Nullable<int> FGS_ID { get; set; }

    public Nullable<int> SO_Id { get; set; }

    public string SO_No { get; set; }

    public string WorkOrderNo { get; set; }

    public string Stage { get; set; }

    public Nullable<bool> WholeBatchRejection { get; set; }

    public string BatchNumber { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> LastModifiedby { get; set; }



    public virtual FinishGoodSery FinishGoodSery { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PostProductionRejectionNote_Details> PostProductionRejectionNote_Details { get; set; }

    public virtual SalesOrder SalesOrder { get; set; }

}

}
