
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PreProduction_QC
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PreProduction_QC()
    {

        this.PreProduction_QC_Details = new HashSet<PreProduction_QC_Details>();

        this.RejectionNotes = new HashSet<RejectionNote>();

    }


    public int ID { get; set; }

    public string QCNumber { get; set; }

    public Nullable<int> MaterialIssue_Id { get; set; }

    public string MaterialIssue_No { get; set; }

    public Nullable<int> ProdIndent_Id { get; set; }

    public string ProdIndent_No { get; set; }

    public Nullable<System.DateTime> QCDate { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PreProduction_QC_Details> PreProduction_QC_Details { get; set; }

    public virtual ProductionIndent ProductionIndent { get; set; }

    public virtual ProductionMaterialIssueNote ProductionMaterialIssueNote { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RejectionNote> RejectionNotes { get; set; }

}

}
