//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMaterialIssueNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionMaterialIssueNote()
        {
            this.PreProduction_QC = new HashSet<PreProduction_QC>();
            this.ProductionMaterialIssueNoteDetails = new HashSet<ProductionMaterialIssueNoteDetail>();
        }
    
        public int ID { get; set; }
        public string ProductionMaterialIssueNoteNo { get; set; }
        public Nullable<System.DateTime> ProductionMaterialIssueNoteDate { get; set; }
        public string Purpose { get; set; }
        public string WorkOrderNumber { get; set; }
        public string QCNumber { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public string SONumber { get; set; }
        public string OtherPurpose { get; set; }
        public Nullable<int> IssueBy { get; set; }
        public string IssueByName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ProductionIndentId { get; set; }
        public string ProductionIndentNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedby { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreProduction_QC> PreProduction_QC { get; set; }
        public virtual ProductionIndent ProductionIndent { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionMaterialIssueNoteDetail> ProductionMaterialIssueNoteDetails { get; set; }
    }
}
