
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ProductionIndentIngredientsDetail
{

    public int ID { get; set; }

    public Nullable<int> ProductionIndentID { get; set; }

    public string QCcheck_1 { get; set; }

    public string QCcheck_2 { get; set; }

    public string QCcheck_3 { get; set; }

    public Nullable<int> ItemId { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string ItemUnit { get; set; }

    public Nullable<double> BatchQuantity { get; set; }

    public Nullable<double> FinalQuantity { get; set; }

    public Nullable<double> Percentage { get; set; }

    public string ProductionCheck { get; set; }

    public Nullable<double> BalanceQuantity { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual Item Item { get; set; }

    public virtual ProductionIndent ProductionIndent { get; set; }

}

}
