
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ProductionMaterialIssueNoteDetail
{

    public int ID { get; set; }

    public Nullable<int> IssueNoteId { get; set; }

    public Nullable<int> ItemId { get; set; }

    public string Item_Code { get; set; }

    public string Item_Name { get; set; }

    public Nullable<double> ItemUnitPrice { get; set; }

    public string ItemUnit { get; set; }

    public string CurrencyName { get; set; }

    public Nullable<int> CurrencyId { get; set; }

    public Nullable<double> CurrencyPrice { get; set; }

    public Nullable<double> QuantityRequested { get; set; }

    public Nullable<double> QuantityIssued { get; set; }

    public Nullable<double> BalanceQty { get; set; }

    public Nullable<double> AvailableStockBeforeIssue { get; set; }

    public Nullable<double> StockAfterIssuing { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> LastModifiedby { get; set; }



    public virtual CurrencyMaster CurrencyMaster { get; set; }

    public virtual Item Item { get; set; }

    public virtual ProductionMaterialIssueNote ProductionMaterialIssueNote { get; set; }

}

}
