//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionIndent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionIndent()
        {
            this.PreProduction_QC = new HashSet<PreProduction_QC>();
            this.ProductionIndentIngredientsDetails = new HashSet<ProductionIndentIngredientsDetail>();
            this.ProductionMaterialIssueNotes = new HashSet<ProductionMaterialIssueNote>();
        }
    
        public int ID { get; set; }
        public string ProductionIndentNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> RaisedBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public string RecipeName { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public string SONo { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<int> TotalBatches { get; set; }
        public string UserName { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreProduction_QC> PreProduction_QC { get; set; }
        public virtual RecipeMaster RecipeMaster { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionIndentIngredientsDetail> ProductionIndentIngredientsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionMaterialIssueNote> ProductionMaterialIssueNotes { get; set; }
    }
}
