//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string PONumber { get; set; }
        public string DespatchMode { get; set; }
        public string TransportationMode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> WithComparison { get; set; }
        public string Freight { get; set; }
        public Nullable<int> ComparisionId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal OtherCharges { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string PaymentsTerms { get; set; }
        public string PaymentTermsDesc { get; set; }
        public string DeliveryTerms { get; set; }
        public string TransitInsurance { get; set; }
        public string PackingAndForwarding { get; set; }
        public string TestToBeOffered { get; set; }
        public string SupervisionTerms { get; set; }
        public string Warranty { get; set; }
        public string DeliveryTermsDesc { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<int> PreparedById { get; set; }
        public Nullable<int> CheckedById { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<decimal> FreightRs { get; set; }
        public Nullable<decimal> FreightGSTPercent { get; set; }
        public Nullable<System.DateTime> CheckedByDate { get; set; }
        public Nullable<System.DateTime> ApprovedByDate { get; set; }
        public string QuatationNo { get; set; }
    }
}
