//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItemsDetail
    {
        public int ID { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public string ItemName { get; set; } // rahul added 
        public string Item_Code { get; set; } // rahul added 
        public Nullable<decimal> ItemQuantity { get; set; }
        public Nullable<decimal> ItemUnitPrice { get; set; }
        //public string ItemTaxValue { get; set; }
        // rahul updated ItemTaxValue string to Nullable<decimal> 
        public Nullable<decimal> ItemTaxValue { get; set; }
        //public Nullable<int> ItemUnit { get; set; }
        // rahul updated ItemUnit Nullable<int> to string
        public string ItemUnit { get; set; }
        public Nullable<decimal> TotalItemCost { get; set; } // rahul added 
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
