//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderAmendment
    {
        public int PurchaseOrderAmendmentId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string PONo { get; set; }
        public string POAmendNo { get; set; }
        public Nullable<System.DateTime> POAmendDate { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentsTerms { get; set; }
        public string DeliveryTerms { get; set; }
        public string TransitInsurance { get; set; }
        public string PackingAndForwarding { get; set; }
        public string TestToBeOffered { get; set; }
        public string SupervisionTerms { get; set; }
        public string Warranty { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ApprovalRemarks { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<int> PreparedById { get; set; }
        public Nullable<int> CheckedById { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> CheckedByDate { get; set; }
        public Nullable<System.DateTime> ApprovedByDate { get; set; }
    }
}
