//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderAmendmentDetail
    {
        public int PurchaseOrderAmendmentDetailsId { get; set; }
        public Nullable<int> PurchaseOrderAmendmentId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string Item_Code { get; set; }
        public Nullable<decimal> ItemUnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> AmendQuantity { get; set; }
        public Nullable<decimal> AmendRate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> AmendDiscount { get; set; }
        public Nullable<decimal> AmendCgst { get; set; }
        public Nullable<decimal> AmendSgst { get; set; }
        public Nullable<decimal> AmendIgst { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual PurchaseOrderAmendment PurchaseOrderAmendment { get; set; }
    }
}
