
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class RejectionNote
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RejectionNote()
    {

        this.DebitNotes = new HashSet<DebitNote>();

        this.RejectionNoteItemDetails = new HashSet<RejectionNoteItemDetail>();

    }


    public int ID { get; set; }

    public string RejectionNoteNo { get; set; }

    public Nullable<System.DateTime> NoteDate { get; set; }

    public Nullable<int> InwardNote_Id { get; set; }

    public string InwardNoteNumber { get; set; }

    public Nullable<int> InwardQCId { get; set; }

    public string InwardQCNumber { get; set; }

    public Nullable<int> SupplierID { get; set; }

    public string SupplierName { get; set; }

    public Nullable<int> PO_ID { get; set; }

    public string PONumber { get; set; }

    public string Attachment { get; set; }

    public string Signature { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> PreProductionQCId { get; set; }

    public string ProductionQCNumber { get; set; }

    public Nullable<int> ProductionMaterialIssueNoteId { get; set; }

    public string ProductionMaterialIssueNoteNo { get; set; }

    public Nullable<int> ProductionIndentId { get; set; }

    public string ProductionIndentNo { get; set; }

    public string QCType { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> LastModifiedby { get; set; }



    public virtual Company Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DebitNote> DebitNotes { get; set; }

    public virtual InwardNote InwardNote { get; set; }

    public virtual InwardQC InwardQC { get; set; }

    public virtual PreProduction_QC PreProduction_QC { get; set; }

    public virtual ProductionIndent ProductionIndent { get; set; }

    public virtual ProductionMaterialIssueNote ProductionMaterialIssueNote { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RejectionNoteItemDetail> RejectionNoteItemDetails { get; set; }

}

}
