//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectionDataSheetMaster
    {
        public int RejectionID { get; set; }
        public Nullable<System.DateTime> RejectionDate { get; set; }
        public int SupplierID { get; set; }
        public string PONumber { get; set; }
        public string DateOfReceving { get; set; }
        public string NameOfMaterial { get; set; }
        public string ManufecturingDate { get; set; }
        public string BestBefore { get; set; }
        public Nullable<int> ItemCategoryID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> TotalRecevingQuantiy { get; set; }
        public Nullable<double> TotalRejectedQuantity { get; set; }
        public Nullable<double> PostRejectedQuantity { get; set; }
        public string ReasonForRejection { get; set; }
        public string CurrectiveAction { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual SupplierMaster SupplierMaster { get; set; }
    }
}
