//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForQuotation
    {
        public int RequestForQuotationId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string RFQNO { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RFQYear { get; set; }
        public string ItemId { get; set; }
        public string QuantityS { get; set; }
        public string SOIDS { get; set; }
        public string PRIDS { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
