
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class RequestForQuotationItemDetail
{

    public int RFQdetailsId { get; set; }

    public Nullable<int> RequestForQuotationId { get; set; }

    public Nullable<int> Item_ID { get; set; }

    public string ItemName { get; set; }

    public string Item_Code { get; set; }

    public Nullable<decimal> ItemQuantity { get; set; }

    public string ItemUnit { get; set; }

    public Nullable<double> ItemUnitPrice { get; set; }

    public string ItemTaxValue { get; set; }

    public Nullable<double> TotalItemCost { get; set; }

    public string HSN_Code { get; set; }

    public Nullable<System.DateTime> DeliveryDate { get; set; }

    public Nullable<int> CurrencyID { get; set; }

    public string CurrencyName { get; set; }

    public Nullable<double> CurrencyPrice { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedByID { get; set; }

    public Nullable<System.DateTime> CreatedByDate { get; set; }

    public Nullable<int> LastModifiedByID { get; set; }

    public Nullable<System.DateTime> LastModifiedByDate { get; set; }



    public virtual CurrencyMaster CurrencyMaster { get; set; }

    public virtual Item Item { get; set; }

    public virtual RequestForQuotation RequestForQuotation { get; set; }

}

}
