//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_VendorDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQ_VendorDetails()
        {
            this.RFQ_Vendor_ItemDetails = new HashSet<RFQ_Vendor_ItemDetails>();
        }
    
        public int RFQ_VendorDetailsId { get; set; }
        public Nullable<int> RequestForQuotationId { get; set; }
        public string RFQNO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> VendorsID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string VendorIDs { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> IGST { get; set; }
        public Nullable<int> TermsAndConditionID { get; set; }
        public string Terms { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> TotalAfterTax { get; set; }
        public Nullable<double> AdvancedPayment { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> CurrencyPrice { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public string DeliveryAddress { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public Nullable<int> LastModifiedByID { get; set; }
        public Nullable<System.DateTime> LastModifiedByDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual RequestForQuotation RequestForQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQ_Vendor_ItemDetails> RFQ_Vendor_ItemDetails { get; set; }
        public virtual TermsAndConditionMaster TermsAndConditionMaster { get; set; }
    }
}
