//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderItemsDetail
    {
        public int ID { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<decimal> ItemQuantity { get; set; }
        public Nullable<decimal> ItemUnitPrice { get; set; }
        public string ItemTaxValue { get; set; }
        public Nullable<int> ItemUnit { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
