//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderPaymentDetail
    {
        public int ID { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> BalancePay { get; set; }
        public Nullable<double> AdvancedPayment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentDetails { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
