
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class SalesOrder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesOrder()
    {

        this.BatchNumberMasters = new HashSet<BatchNumberMaster>();

        this.BatchPlanningMasters = new HashSet<BatchPlanningMaster>();

        this.CreditNotes = new HashSet<CreditNote>();

        this.DeliveryChallans = new HashSet<DeliveryChallan>();

        this.PostProductionRejectionNotes = new HashSet<PostProductionRejectionNote>();

        this.ProductionIndents = new HashSet<ProductionIndent>();

        this.ProductionMaterialIssueNotes = new HashSet<ProductionMaterialIssueNote>();

        this.SalesOrderItemsDetails = new HashSet<SalesOrderItemsDetail>();

        this.SalesOrderPaymentDetails = new HashSet<SalesOrderPaymentDetail>();

        this.StockMasters = new HashSet<StockMaster>();

    }


    public int SalesOrderId { get; set; }

    public string SONo { get; set; }

    public Nullable<System.DateTime> SODate { get; set; }

    public Nullable<System.DateTime> DeliveryDate { get; set; }

    public Nullable<int> ClientID { get; set; }

    public string CompanyName { get; set; }

    public Nullable<double> CGST { get; set; }

    public Nullable<double> SGST { get; set; }

    public Nullable<double> IGST { get; set; }

    public Nullable<int> TermsAndConditionID { get; set; }

    public string Terms { get; set; }

    public string SalesOrderStatus { get; set; }

    public Nullable<bool> Cancelled { get; set; }

    public string ReasonForCancellation { get; set; }

    public Nullable<bool> DraftFlag { get; set; }

    public Nullable<int> Amendment { get; set; }

    public string DeliveryAddress { get; set; }

    public string SupplierAddress { get; set; }

    public Nullable<decimal> AdvancedPayment { get; set; }

    public Nullable<decimal> GrandTotal { get; set; }

    public Nullable<decimal> TotalAfterTax { get; set; }

    public Nullable<int> LocationId { get; set; }

    public string LocationName { get; set; }

    public string Attachment { get; set; }

    public string QuotationRef { get; set; }

    public Nullable<int> CurrencyID { get; set; }

    public string CurrencyName { get; set; }

    public Nullable<double> CurrencyPrice { get; set; }

    public Nullable<decimal> OtherTax { get; set; }

    public string Signature { get; set; }

    public Nullable<int> ApprovedBy { get; set; }

    public Nullable<System.DateTime> ApprovedDate { get; set; }

    public Nullable<int> CheckedBy { get; set; }

    public Nullable<System.DateTime> CheckedDate { get; set; }

    public string DispatchMode { get; set; }

    public Nullable<int> InquiryID { get; set; }

    public string InquiryNumber { get; set; }

    public string WorkOrderNo { get; set; }

    public string WorkOrderType { get; set; }

    public Nullable<double> DiscountPercentage { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BatchNumberMaster> BatchNumberMasters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BatchPlanningMaster> BatchPlanningMasters { get; set; }

    public virtual Company Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditNote> CreditNotes { get; set; }

    public virtual CurrencyMaster CurrencyMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeliveryChallan> DeliveryChallans { get; set; }

    public virtual InquiryMaster InquiryMaster { get; set; }

    public virtual LocationMaster LocationMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PostProductionRejectionNote> PostProductionRejectionNotes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductionIndent> ProductionIndents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductionMaterialIssueNote> ProductionMaterialIssueNotes { get; set; }

    public virtual TermsAndConditionMaster TermsAndConditionMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SalesOrderItemsDetail> SalesOrderItemsDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SalesOrderPaymentDetail> SalesOrderPaymentDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StockMaster> StockMasters { get; set; }

}

}
