//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransfer_M
    {
        public int StockTransferMId { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public string TransferNo { get; set; }
        public string TransferType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FromSite { get; set; }
        public Nullable<int> ToSite { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AuthorisedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedby { get; set; }
    }
}
