//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment_M
    {
        public int StockAdjustmentMId { get; set; }
        public string AdjustmentVoucherNo { get; set; }
        public Nullable<System.DateTime> AdjustmentVoucherDate { get; set; }
        public Nullable<System.DateTime> AdjustmentVoucherWEF { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedby { get; set; }
    }
}
