//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMaster
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public Nullable<double> StockQuantity { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> InwardNoteId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual InwardNote InwardNote { get; set; }
        public virtual Item Item { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
