
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class StockMaster
{

    public int ID { get; set; }

    public int ItemID { get; set; }

    public string ItemName { get; set; }

    public string Item_Code { get; set; }

    public Nullable<decimal> ItemUnitPrice { get; set; }

    public string ItemUnit { get; set; }

    public Nullable<double> StockQuantity { get; set; }

    public Nullable<int> GRNId { get; set; }

    public Nullable<int> PO_Id { get; set; }

    public string PO_Number { get; set; }

    public string SaledOrder_Number { get; set; }

    public Nullable<int> SO_Id { get; set; }

    public Nullable<int> CurrencyId { get; set; }

    public string CurrencyName { get; set; }

    public Nullable<double> CurrencyPrice { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }



    public virtual CurrencyMaster CurrencyMaster { get; set; }

    public virtual GRN_Master GRN_Master { get; set; }

    public virtual Item Item { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }

    public virtual SalesOrder SalesOrder { get; set; }

}

}
