//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ValveTestRecordsold_M
    {
        public int RecordId { get; set; }
        public Nullable<int> ValveId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<System.DateTime> TestingDate { get; set; }
        public Nullable<System.DateTime> TestingDueDate { get; set; }
        public string TestReportNumber { get; set; }
        public string TagNumber { get; set; }
        public string Make { get; set; }
        public string ValveSrNumber { get; set; }
        public string SetPressure { get; set; }
        public string FluidandState { get; set; }
        public string CDTP { get; set; }
        public string BackPressure { get; set; }
        public string SpringNr { get; set; }
        public string OPTemperature { get; set; }
        public Nullable<int> SealingStatus { get; set; }
        public Nullable<int> TestCategoryId { get; set; }
        public Nullable<int> SubTestCategoryId { get; set; }
        public Nullable<int> ValveTypeId { get; set; }
        public string Material { get; set; }
        public string Section { get; set; }
        public string PressureClass { get; set; }
        public string MakePressureGauge { get; set; }
        public string SerialNumber { get; set; }
        public string Range { get; set; }
        public string PressureGaugeType { get; set; }
        public Nullable<System.DateTime> CalibrationOn { get; set; }
        public Nullable<System.DateTime> CalibrationDueOn { get; set; }
        public string TestStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
