//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserDetails_M
    {
        public int UserDetailsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserCode { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Name { get; set; }
    
        public virtual Tbl_Designation_M Tbl_Designation_M { get; set; }
        public virtual Tbl_Organization_M Tbl_Organization_M { get; set; }
        public virtual Tbl_User_M Tbl_User_M { get; set; }
    }
}
