//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TestComponent_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TestComponent_M()
        {
            this.Tbl_ValveTestRecordsEntry_M = new HashSet<Tbl_ValveTestRecordsEntry_M>();
            this.Tbl_ValveTestRecordsEntry_M1 = new HashSet<Tbl_ValveTestRecordsEntry_M>();
        }
    
        public int TestComponentId { get; set; }
        public Nullable<int> TestComponentCategoryId { get; set; }
        public string Make { get; set; }
        public string SerialNumber { get; set; }
        public string Range { get; set; }
        public string PressureGauge { get; set; }
        public Nullable<System.DateTime> CalibrationOn { get; set; }
        public Nullable<System.DateTime> CalibrationDueOn { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string TestComponentName { get; set; }
    
        public virtual Tbl_TestComponentCategory_M Tbl_TestComponentCategory_M { get; set; }
        public virtual Tbl_Units_M Tbl_Units_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ValveTestRecordsEntry_M> Tbl_ValveTestRecordsEntry_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ValveTestRecordsEntry_M> Tbl_ValveTestRecordsEntry_M1 { get; set; }
    }
}
