//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InVanWebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PressureValues_T
    {
        public long Id { get; set; }
        public Nullable<int> TestRecordId { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> DecimalPoint { get; set; }
        public Nullable<int> SetPoint1 { get; set; }
        public Nullable<int> SerPoint2 { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Tbl_ValveTestRecordsEntry_M Tbl_ValveTestRecordsEntry_M { get; set; }
    }
}
