
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class VegWasherDosageLog
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<decimal> VegWasher1SolutionAMl { get; set; }

    public Nullable<decimal> VegWasher1SolutionBMl { get; set; }

    public string NameOfItem1 { get; set; }

    public string WashingTime1 { get; set; }

    public string Ppm1 { get; set; }

    public Nullable<decimal> VegWasher2SolutionAMl { get; set; }

    public Nullable<decimal> VegWasher2SolutionBMl { get; set; }

    public string NameOfItem2 { get; set; }

    public string WashingTime2 { get; set; }

    public string Ppm2 { get; set; }

    public string Remark { get; set; }

    public string VerifyByName { get; set; }

    public Nullable<bool> Isdeleted { get; set; }

    public Nullable<int> Createdby { get; set; }

    public Nullable<System.DateTime> Createddate { get; set; }

    public Nullable<int> Lastmodifiedby { get; set; }

    public Nullable<System.DateTime> Lastmodifieddate { get; set; }

}

}
