
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Vw_SalesOrder_PaymentDetails
{

    public int ID { get; set; }

    public Nullable<int> SalesOrderId { get; set; }

    public string SONumber { get; set; }

    public string CompanyName { get; set; }

    public Nullable<double> GrandTotal { get; set; }

    public string InvoiceNo { get; set; }

    public Nullable<double> InvoiceAmount { get; set; }

    public Nullable<double> AmountPaid { get; set; }

    public Nullable<double> BalancePay { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string PaymentMode { get; set; }

    public string PaymentStatus { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> PaymentDueDate { get; set; }

}

}
