
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Vw_Sotck_Report
{

    public int ID { get; set; }

    public string Item_Code { get; set; }

    public string ItemName { get; set; }

    public string ItemCategory { get; set; }

    public Nullable<decimal> ItemUnitPrice { get; set; }

    public Nullable<double> StockQuantity { get; set; }

    public string ItemUnit { get; set; }

    public Nullable<double> InventoryValue { get; set; }

    public Nullable<double> ReOrderLevel { get; set; }

    public int ItemID { get; set; }

}

}
