
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class WorkOrderDetail
{

    public int WorkOrderDetailsId { get; set; }

    public Nullable<int> WorkOrderId { get; set; }

    public string ItemType { get; set; }

    public Nullable<int> ItemId { get; set; }

    public string ItemName { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public Nullable<int> UnitId { get; set; }

    public Nullable<decimal> Rate { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> CGST { get; set; }

    public Nullable<decimal> SGST { get; set; }

    public Nullable<decimal> IGST { get; set; }

    public Nullable<decimal> Value { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }



    public virtual WorkOrder WorkOrder { get; set; }

}

}
