
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InVanWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class WorkOrder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WorkOrder()
    {

        this.COAMasters = new HashSet<COAMaster>();

        this.WorkOrderDetails = new HashSet<WorkOrderDetail>();

    }


    public int WorkOrderId { get; set; }

    public Nullable<int> OrganisationId { get; set; }

    public Nullable<int> BranchId { get; set; }

    public Nullable<int> SupplierId { get; set; }

    public string SONo { get; set; }

    public string INNo { get; set; }

    public Nullable<System.DateTime> WODate { get; set; }

    public string WONo { get; set; }

    public string DespatchMode { get; set; }

    public string TransportationMode { get; set; }

    public string Freight { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<decimal> Tax { get; set; }

    public Nullable<decimal> OtherCharges { get; set; }

    public Nullable<decimal> GrandTotal { get; set; }

    public string PaymentsTerms { get; set; }

    public string PaymentTermsDesc { get; set; }

    public string DeliveryTerms { get; set; }

    public string DeliveryTermsDesc { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> ApprovedById { get; set; }

    public Nullable<int> PreparedById { get; set; }

    public Nullable<int> CheckedById { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public Nullable<decimal> FreightRs { get; set; }

    public Nullable<decimal> FreightGSTPercent { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<COAMaster> COAMasters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get; set; }

}

}
